[project]
name = "09-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "M E Hasareli", email = "eran.hasarali.2001@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "openai>=3.19.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
09-25 = "09_25:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
